### ISSUE TITLE
Checklist for publishing

### ISSUE THREAD

**Issue by MindTooth** [tomrtk/fish-code#31]
- [ ] ~~Fix README in each package~~
- [x]  Add LICENSE - ([Fix](https://github.com/MindTooth/fish-code/pull/30))
- [ ]  Decide where to publish, check if NINA have input?
- [ ]  Naming?

**Comment by tomrtk** [comment]
- [x] Cleanup in labels. Remove eg. `reports` labels etc.
